### ISSUE TITLE
CSS总结

### ISSUE THREAD

**Issue by Hiufan** [Hiufan/blog#2]
### CSS书写顺序

1.位置属性(position, top, right, z-index, display, float等)
2.大小(width, height, padding, margin)
3.文字系列(font, line-height, letter-spacing, color- text-align等)
4.背景(background, border等)
5.其他(animation, transition等)

``` CSS
/* Not recommended */
.example{
    color:red;
    z-index:-1;
    background-color:#9e0;
    display:inline-block;
    font-size:1.5em;
}

/* Recommended */
.example{
    z-index:-1;
    display:inline-block;
    font-size:1.5em;
    color:red;
    background-color:#9e0;
}
```
### 使用CSS缩写属性

``` CSS
/* Not recommended */
.list-box{
    line-height:1.6;
    padding-bottom:2em;
    padding-left:1em;
    padding-right:1em;
    padding-top:0;
    font-family:serif;
    font-size:100%;
    border-top-style:none;
}
/* Recommended */
.list-box{
    padding: 0 1em 2em;
    font:100%/1.6 serif;
    border-top:0;
}
```
