### ISSUE TITLE
base.css（from tencent）

### ISSUE THREAD

**Issue by Hiufan** [Hiufan/blog#3]
``` css
body,ol,ul,h1,h2,h3,h4,h5,h6,p,th,td,dl,dd,form,fieldset,legend,input,textarea,select {
    margin:0;
    padding:0
}
body {
    font:12px "宋体","Arial Narrow",HELVETICA;
    background:#fff;
    -webkit-text-size-adjust:100%;
}
a {
    text-decoration:none
}
a:hover {
    text-decoration:underline
}
em {
    font-style:normal
}
li {
    list-style:none
}
img {
    border:0;
    vertical-align:middle
}
table {
    border-collapse:collapse;
    border-spacing:0
}
p {
    word-wrap:break-word
}
.undis {
    display:none
}
.dis {
    display:block
}
.ind {
    text-indent:2em
}
.Q-red a,a.Q-red {
    color:#bd0a01
}
.Q-black a,a.Q-black {
    color:#000
}
.layout:after,.hd:after,.bd:after,.ft:after,.cf:after,.Q-tList:after,.Q-tList ul:after,.Q-tList ol:after,.Q-pList:after,.Q-pList ul:after,.Q-tpList:after,.Q-tpList ul:after,.Q-tpWrap:after {
    content:"";
    display:table;
    clear:both
}
.layout,.hd,.bd,.ft,.cf,.Q-tList,.Q-tList ul,.Q-tList ol,.Q-pList,.Q-pList ul,.Q-tpList,.Q-tpList ul,.Q-tpWrap {
    *zoom:1
}
@media screen {
    .fl,.layout .fl,.chief {
    float:left;
    display:inline
}
.fr,.layout .fr,.extra {
    float:right;
    display:inline
}
.layout {
    width:960px;
    margin:0 auto
}
.Q-g4 .chief {
    width:780px
}
.Q-g4 .extra {
    width:170px
}
.Q-g8 .chief {
    width:637px
}
.Q-g8 .main,.Q-g8 .extra {
    width:313px
}
.Q-g8 .sub {
    width:314px
}
.Q-g12 .chief,.Q-g12 .extra {
    width:475px
}
.Q-g14 .chief {
    width:570px
}
.Q-g14 .extra {
    width:380px
}
.Q-g16 .chief {
    width:640px
}
.Q-g16 .main {
    width:380px
}
.Q-g16 .sub {
    width:250px
}
.Q-g16 .extra {
    width:310px
}
.Q-g17a .chief,.Q-g17b .chief,.Q-g17c .chief {
    width:700px
}
.Q-g17a .main {
    width:380px
}
.Q-g17a .sub {
    width:310px
}
.Q-g17a .extra,.Q-g17b .extra,.Q-g17c .extra {
    width:250px
}
.Q-g17b .main,.Q-g17b .sub {
    width:345px
}
.Q-g17c .main {
    width:440px
}
.Q-g17c .sub {
    width:250px
}
.Q-g24 .chief {
    width:960px
}
.Q-g16a-a .chief {
    width:650px
}
.Q-g16a-a .main {
    width:370px
}
.Q-g16a-a .sub {
    width:260px
}
.Q-g16a-a .extra,.Q-g16a-b .extra,.Q-g16a-c .extra,.Q-g16b-a .extra,.Q-g16b-b .extra {
    width:300px
}
.Q-g16a-b .chief,.Q-g16a-c .chief {
    width:680px
}
.Q-g16a-b .main {
    width:380px
}
.Q-g16a-b .sub {
    width:280px
}
.Q-g16a-c .main {
    width:350px
}
.Q-g16a-c .sub {
    width:310px
}
.Q-g16a-d .chief {
    width:710px
}
.Q-g16a-d .main {
    width:360px
}
.Q-g16a-d .sub {
    width:330px
}
.Q-g16a-d .extra {
    width:250px
}
.Q-g16b-a .chief {
    width:640px
}
.Q-g16b-b .chief {
    width:660px
}
.hd h2,.hd h3 {
    float:left;
    display:inline
}
.f12 {
    font-size:12px
}
.f14 {
    font-size:14px
}
.f16 {
    font-size:16px
}
.f18 {
    font-size:18px
}
.f20 {
    font-size:20px
}
.l16 {
    line-height:16px
}
.l17 {
    line-height:17px
}
.l18 {
    line-height:18px
}
.l19 {
    line-height:19px
}
.l20 {
    line-height:20px
}
.l21 {
    line-height:21px
}
.l22 {
    line-height:22px
}
.l23 {
    line-height:23px
}
.l24 {
    line-height:24px
}
.l25 {
    line-height:25px
}
.l26 {
    line-height:26px
}
.l27 {
    line-height:27px
}
.l28 {
    line-height:28px
}
.l29 {
    line-height:29px
}
.l30 {
    line-height:30px
}
.Q-hot,.Q-tList {
    margin:0 10px
}
.Q-hot h2 {
    font:normal 18px/28px simhei;
    text-align:center
}
.Q-hot h2.l30 {
    font-size:20px
}
.Q-tList span,.Q-tpList li span {
    float:right
}
.Q-pList li {
    float:left;
    display:inline;
    text-align:center
}
.Q-pList a {
    display:block
}
.Q-pList p a {
    display:inline
}
.Q-tpList em {
    font-weight:bold
}
.Q-tpList .pic {
    float:left;
    margin-right:10px;
    overflow:hidden;
    display:inline;
    text-align:center
}
.Q-tpList .pic img {
    border:1px solid #cbcbcb;
    display:block
}
.Q-vBg {
    width:100%;
    height:21px;
    position:relative;
    margin-top:-21px;
    font:12px/21px "宋体","Arial Narrow",HELVETICA;
    background:rgba(0,0,0,0.6);
    filter:progid:DXImageTransform.Microsoft.gradient( Q-gradientType = 0,startColorstr = '#80000000',endColorstr = '#80000000') \9;
    text-align:right;
    cursor:pointer
}
.Q-vBg b {
    display:block;
    position:absolute;
    width:21px;
    height:21px;
    top:0;
    left:0;
    cursor:pointer
}
.Q-vBg span {
    padding:0 5px;
    color:#fff;
    cursor:pointer
}
.Q-line {
    height:0;
    font:0/0 Arial;
    overflow:hidden;
    clear:both;
    border-bottom:1px dashed #ccc
}
.Q-iDot li,.Q-iDotBlue li,.Q-iDotGray li,.Q-iTqq li,.Q-iVideo li,.Q-iVideoBlue li,.Q-iVideoDeep li,.Q-iVideoGreen li {
    background:url(http://mat1.gtimg.com/news/base2011/img/i.png) no-repeat
}
.Q-iDotBlue li {
    background-position:0 -30px
}
.Q-iTqq li {
    background-position:0 -60px
}
.Q-iVideo li {
    background-position:0 -90px
}
.Q-iVideoBlue li {
    background-position:0 -120px
}
.Q-iVideoDeep li {
    background-position:0 -210px
}
.Q-iDotGray li {
    background-position:0 -180px
}
.Q-iVideoGreen li {
    background-position:0 -240px
}
.mt10 {
    margin-top:10px
}
.mb10 {
    margin-bottom:10px
}
}/*  |xGv00|8dad2e4e157648a4dc51659fdbf94229 */
```
